version: '3.8'
services:
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  netbird:
    image: netbirdio/netbird:latest
    hostname: homelab
    network_mode: host
    restart: unless-stopped
    cap_add: 
      - NET_ADMIN 
      - SYS_ADMIN 
      - SYS_RESOURCE  
    volumes: 
      - /var/netbird:/etc/netbird 
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
  restic:
    image: mazzolino/restic:latest
    restart: unless-stopped
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RUN_ON_STARTUP: "true"
      RESTIC_COMPRESSION: auto
      RESTIC_BACKUP_SOURCES: /backup
      RESTIC_BACKUP_ARGS: >-
        --tag docker-volumes
        --verbose
      BACKUP_CRON: "0 30 3 * * *"
      TZ: "America/Los_Angeles"
    volumes: 
      - /var/vaultwarden:/backup/vaultw
      - /var/syncthing:/backup/syncthing
      - /var/portainer:/backup/portainer
      - /var/pihole:/backup/pihole
      - /var/pihole-dnsmasq:/backup/pihole-dnsmasq
      - /var/uptime-kuma:/backup/uptime-kuma
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    volumes:
      - /var/uptime-kuma:/app/data
    restart: unless-stopped
networks:
  default:
    external: true
    name: proxy

