services:
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      TZ: 'America/Los Angeles'
    volumes:
      - /var/pihole:/etc/pihole
      - /var/pihole-dnsmasq:/etc/dnsmasq.d
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  restic:
    image: mazzolino/restic:latest
    restart: unless-stopped
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RUN_ON_STARTUP: "true"
      RESTIC_COMPRESSION: auto
      RESTIC_BACKUP_SOURCES: /backup
      RESTIC_BACKUP_ARGS: >-
        --tag docker-volumes
        --verbose
      BACKUP_CRON: "0 30 3 * * *"
      TZ: "America/Los_Angeles"
    volumes: 
      - /var/vaultwarden:/backup/vaultw
      - /var/syncthing:/backup/syncthing
      - /var/pihole:/backup/pihole
      - /var/pihole-dnsmasq:/backup/pihole-dnsmasq
      - /var/uptime-kuma:/backup/uptime-kuma
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    volumes:
      - /var/uptime-kuma:/app/data
    restart: unless-stopped 
networks:
  default:
    external: true
    name: proxy

