services:
  restic:
    image: mazzolino/restic:latest
    restart: unless-stopped
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RUN_ON_STARTUP: "true"
      RESTIC_COMPRESSION: auto
      RESTIC_BACKUP_SOURCES: /backup
      RESTIC_BACKUP_ARGS: >-
        --tag docker-volumes
        --verbose
      BACKUP_CRON: "0 30 3 * * *"
      TZ: "America/Los_Angeles"
    volumes: 
      - /var/vaultwarden:/backup/vaultw
      - /var/copyparty:/backup/copyparty
      - /var/pihole:/backup/pihole
      - /var/pihole-dnsmasq:/backup/pihole-dnsmasq
      - /var/uptime-kuma:/backup/uptime-kuma
